#!/bin/bash


blockMesh
sed -r -i 's/defaultFaces/outlet/g' constant/polyMesh/boundary



decomposePar -force
mpirun -np 3 reactingFoam -parallel


decomposePar -force -fileHandler collated
mpirun -np 3 reactingFoam -parallel -fileHandler collated